### ISSUE TITLE
Marseille is broken in Safari 6.0.3

### ISSUE THREAD

**Issue by mathias-erik** [Edicy/design-marseille#1]
http://forum.edicy.com/forums/design-and-content/topics/search-pop-up#post_1523

Marseille lay-out seems to jump depending on the browser window size
Marseille small window: looks ok http://i.imgur.com/FmKfBXd.png
Marseille bigger window: looks messed-up: http://i.imgur.com/I6J6S05.png

**Comment by kaspar-naaber** [comment]
Safari 6 is a legacy browser that is not supported anymore. We will not fix that issue.
